// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/salary-grid/AppendixGrid.tsx": () => import("../components/mockups/salary-grid/AppendixGrid.tsx"),
  "./components/mockups/salary-grid/SalaryCurveAnalysis.tsx": () => import("../components/mockups/salary-grid/SalaryCurveAnalysis.tsx"),
  "./components/mockups/salary-grid/SummaryFirstDrilldown.tsx": () => import("../components/mockups/salary-grid/SummaryFirstDrilldown.tsx")
};
